apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yatai.envname" . }}
  labels:
  {{- include "yatai.labels" . | nindent 4 }}
type: Opaque
stringData:
  YATAI_INITIALIZATION_TOKEN: {{ include "yatai.initializationToken" . | quote }}
  SESSION_SECRET_KEY: {{ include "yatai.sessionSecretKey" . | quote }}

  PG_HOST: {{ .Values.postgresql.host | quote }}
  PG_DATABASE: {{ .Values.postgresql.database | quote }}
  PG_PORT: {{ .Values.postgresql.port | quote }}
  PG_SSLMODE: {{ .Values.postgresql.sslmode | quote }}
  PG_USER: {{ .Values.postgresql.user | quote }}
  {{- if not .Values.postgresql.passwordExistingSecretName }}
  PG_PASSWORD: {{ .Values.postgresql.password | quote }}
  {{- end }}
  PG_MAX_OPEN_CONNS: {{ .Values.postgresql.maxOpenConns | quote }}
  PG_MAX_IDLE_CONNS: {{ .Values.postgresql.maxIdleConns | quote }}
  PG_CONN_MAX_LIFETIME: {{ .Values.postgresql.connMaxLifetime | quote }}

  S3_ENDPOINT: {{ .Values.s3.endpoint | quote }}
  S3_REGION: {{ .Values.s3.region | quote }}
  S3_BUCKET_NAME: {{ .Values.s3.bucketName | quote }}
  S3_SECURE: {{ .Values.s3.secure | quote }}
  {{- if not .Values.s3.accessKeyExistingSecretName }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | quote }}
  {{- end }}
  {{- if not .Values.s3.secretKeyExistingSecretName }}
  S3_SECRET_KEY: {{ .Values.s3.secretKey | quote }}
  {{- end }}

  TRANSMISSION_STRATEGY: {{ .Values.transmissionStrategy | quote }}

  INTERNAL_IMAGES_DEBUGGER: {{ .Values.internalImages.debugger | quote }}
